from commands import *


load(0x8000, "slices/bank6.bin", "6502")

config.set_lower_case(False)

# Remove all extras
config.set_label_references(False)
config.set_show_autogenerated_labels(False)
config.set_show_all_labels(False)
config.set_inline_comment_column(50)
config.set_subroutine_header("*" * 78)

entry(0x8000)
string(0x8007, 5)

entry(0x800C)
entry(0x800F)
entry(0x8015)
entry(0x8018)
entry(0x801B)
entry(0x801E)
byte(0x88BC, 0x895A - 0x88BC)
entry(0x89D1)

entry(0xA91B)

exec(open('py8dis-scripts/common-variables.py').read())

go()
